# Generated by Django 3.1.3 on 2020-11-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('block', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.CharField(max_length=15)),
                ('logitute', models.CharField(max_length=15)),
            ],
        ),
    ]
