# Generated by Django 3.1.4 on 2020-12-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, null=True, upload_to='photos/packages/original')),
                ('normal', models.ImageField(blank=True, null=True, upload_to='photos/packages/thumbs')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='photos/packages/thumbs')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('tample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temple')),
            ],
        ),
    ]
